import type {Metadata} from "next";
import {Schibsted_Grotesk, Jomolhari, Poppins} from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";

const christenedGrotesque = Schibsted_Grotesk({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Poppins({
    variable: "--font-geist-poppins",
    subsets: ["latin"],
    weight: ["400", "700", "100", "200", "300", "500", "600", "800", "900"],
});


const jhomolHari = Jomolhari({
    weight:  "400",
    variable: "--font-Jomolhari"
})

export const metadata: Metadata = {
    title: {
        default: "Zenco.com",
        template: "%s | Zenco.com",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${christenedGrotesque.variable} ${geistMono.variable} ${jhomolHari.variable} min-h-screen antialiased`}
        >
        <Header/>
        <main className="w-full relative max-w-lvw">
            {children}
        </main>
        </body>
        </html>
    );
}
