import type {Metadata} from "next";
import {Geist_Mono, Lato, Schibsted_Grotesk, Jomolhari} from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";

const christenedGrotesque = Schibsted_Grotesk({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const latoFont = Lato({
    subsets: ["latin"],
    variable: "--font-Lato",
    weight:["100" , "300", "400" , "700" , "900"]
})

const jhomolHari = Jomolhari({
    weight:  "400",
    variable: "--font-Jomolhari"
})

export const metadata: Metadata = {
    title: {
        default: "Zenco.com",
        template: "%s | Zenco.com",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${christenedGrotesque.variable} ${geistMono.variable} ${latoFont.variable} min-h-screen antialiased`}
        >
        <Header/>
        <main className="w-full relative max-w-lvw">
            {children}
        </main>
        </body>
        </html>
    );
}
