import type { Metadata } from "next";
import { Schibsted_Grotesk, Poppins, Kalnia } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";

const christenedGrotesque = Schibsted_Grotesk({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Poppins({
  variable: "--font-geist-poppins",
  subsets: ["latin"],
  weight: ["400", "700", "100", "200", "300", "500", "600", "800", "900"],
});


const kalnia = Kalnia({
    weight: ["400", "700", "100", "200", "300", "500", "600"],
    variable: "--font-kalnia",
});

export const metadata: Metadata = {
  title: {
    default: "Zenco.com",
    template: "%s | Zenco.com",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${christenedGrotesque.variable} ${geistMono.variable} ${kalnia.className} min-h-screen antialiased`}
      >
        <Header />
        <main className="w-full relative max-w-lvw">{children}</main>
      </body>
    </html>
  );
}
